spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    username: postgres
    password: 291197
    url: jdbc:postgresql://localhost:5432/authuser
server:
  port: 3333